<?php

return [
    'sword' => [
        'name' => 'ソードマン',
        'desc' => '火力は最高だが回復も耐久も低い',
        'color' => '#e0555a',
        'icon' => 'sword',
        'base_hp' => 80,
        'hp_growth' => 4,
        'base_power' => 14,
        'power_growth' => 1.4,
        'base_int' => 4,
        'int_growth' => 0.30,
    ],
    'shield' => [
        'name' => 'シールダー',
        'desc' => '耐久と回復に優れ奥まで進める',
        'color' => '#4a90d9',
        'icon' => 'shield',
        'base_hp' => 130,
        'hp_growth' => 9,
        'base_power' => 9,
        'power_growth' => 0.8,
        'base_int' => 10,
        'int_growth' => 0.80,
    ],
    'mage' => [
        'name' => 'メイジ',
        'desc' => '育てるほど火力が伸びる大器晩成',
        'color' => '#a06fd6',
        'icon' => 'staff',
        'base_hp' => 85,
        'hp_growth' => 5,
        'base_power' => 10,
        'power_growth' => 1.8,
        'base_int' => 6,
        'int_growth' => 0.50,
    ],
    'balance' => [
        'name' => 'バランサー',
        'desc' => '平均的で扱いやすい',
        'color' => '#4CAF50',
        'icon' => 'scales',
        'base_hp' => 100,
        'hp_growth' => 6,
        'base_power' => 11,
        'power_growth' => 1.1,
        'base_int' => 7,
        'int_growth' => 0.55,
    ],
];
